### ISSUE TITLE
Forgotten len()

### ISSUE THREAD

**Issue by Sheidbrink** [zappala/messaging-service-python#3]
in messageDaemon.py line 141:
 if data > length:
    self.cache = data[length:]
    data = data[:length]
else:
    self.cache = ''

Should be

 if len(data) > length:
    self.cache = data[length:]
    data = data[:length]
else:
    self.cache = ''

However, this if branch in unneeded because if it is evaluated true (which it currently always is) will do the same thing if it should have been evaluated false.

**Comment by zappala** [comment]
Thanks, I fixed this.
